name: sporteve
description: A modern sports news app built with Flutter

publish_to: 'none'

version: 1.0.2+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Requests
  http: ^1.1.0
  
  # Image Loading
  cached_network_image: ^3.3.0
  
  # Date Formatting
  intl: ^0.18.1
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Firebase - Updated to latest compatible versions for web
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.5
  firebase_messaging: ^14.9.2
  google_sign_in: ^6.3.0
  
  # Explicitly add Firebase web support
  firebase_core_web: ^2.13.0
  firebase_auth_web: ^5.11.5
  cloud_functions_web: ^4.6.6
  firebase_storage: ^11.7.0
  file_picker: ^8.0.0+1
  cloud_functions: ^4.7.6
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # URL Launcher
  url_launcher: ^6.2.1
  
  # Sharing
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  
  # Image generation
  widgets_to_image: ^1.0.0
  
  # Device and app info for feedback
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  
  # Password hashing (for admin auth)
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Icon and splash screen generators
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

# Force newer dependency versions to resolve Android compatibility issues
dependency_overrides:
  # Force newer versions that support Android 34+
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  
  assets:
    - images/
    - assets/

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
  windows:
    generate: false
    remove_alpha_ios: true

# Splash Screen Configuration  
flutter_native_splash:
  color: "#2196F3"
  web: false

