name: sporteve
description: A modern sports news app built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Requests
  http: ^1.1.0
  
  # Image Loading
  cached_network_image: ^3.3.0
  
  # Date Formatting
  intl: ^0.18.1
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # URL Launcher
  url_launcher: ^6.2.1
  
  # Sharing
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  
  # Image generation
  widgets_to_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - logos/
    - images/

